# -*- coding: utf-8 -*-
"""urban forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_353GTHl8HFRm9nOXEKAFtd-JLDP_4Es
"""

# =====================================================
# DATA FUSION: URBANIZATION + FOREST DATA FOR KERALA
# Complete Google Colab Python Version
# =====================================================

# Install and import required libraries
!pip install geemap earthengine-api -q

import ee
import geemap
import geemap.foliumap as geemap
import time
import matplotlib.pyplot as plt
import numpy as np

# Authenticate and initialize Earth Engine
try:
    ee.Initialize()
except:
    ee.Authenticate()
    ee.Initialize(project='ee-vineesh')

print('✅ Earth Engine initialized successfully!\n')

# =====================================================
# DEFINE AOI
# =====================================================

# Define AOI
aoi = ee.FeatureCollection("projects/ee-vineesh/assets/kerala")
crs = 'EPSG:32643'  # WGS 84 / UTM zone 43N

print('📍 Study Area: Kerala, India')
print(f'   CRS: {crs}\n')

# =====================================================
# LOAD AND CLIP URBANIZATION DATA (GHSL)
# =====================================================

print('📥 Loading GHSL urbanization data...')

# Load GHSL data for different epochs
ghsl_2010 = ee.Image("JRC/GHSL/P2023A/GHS_SMOD_V2-0/2010").select('smod_code')
ghsl_2020 = ee.Image("JRC/GHSL/P2023A/GHS_SMOD_V2-0/2020").select('smod_code')

# Using 2010 as proxy for 2008 and 2020 as proxy for 2018 (closest available)
smod_2008 = ghsl_2010.clip(aoi)
smod_2018 = ghsl_2020.clip(aoi)

print('✅ GHSL data loaded')

# =====================================================
# LOAD AND CLIP FOREST DATA (Hansen)
# =====================================================

print('📥 Loading Hansen forest data...')

hansenDataset = ee.Image('UMD/hansen/global_forest_change_2024_v1_12')

# Tree cover in 2000
treeCover2000 = hansenDataset.select('treecover2000').clip(aoi)

# Loss year
lossYear = hansenDataset.select('lossyear').clip(aoi)

# Calculate tree cover for 2008 (losses from 2001-2008, lossyear 1-8)
loss_by_2008 = lossYear.lte(8).And(lossYear.gte(1))
treeCover2008 = treeCover2000.where(loss_by_2008, 0)

# Calculate tree cover for 2018 (losses from 2001-2018, lossyear 1-18)
loss_by_2018 = lossYear.lte(18).And(lossYear.gte(1))
treeCover2018 = treeCover2000.where(loss_by_2018, 0)

# Create forest masks (tree cover > 30%)
forest2008 = treeCover2008.gte(30)
forest2018 = treeCover2018.gte(30)

print('✅ Forest data loaded\n')

# =====================================================
# DATA FUSION: CREATE COMBINED CLASSIFICATION
# =====================================================
# Classes:
# 1 = Urban (SMOD 30: Urban Centre)
# 2 = Peri-Urban (SMOD 21, 22, 23: Suburban, Semi-dense, Dense Urban Cluster)
# 3 = Rural (SMOD 11, 12, 13: Rural areas)
# 4 = Natural Forest (Forest areas outside urban/peri-urban)

print('🔄 Creating fused classification...')

# Function to create fused classification
def createFusedClassification(smod, forest, year):
    """
    Create fused classification combining SMOD and forest data

    Args:
        smod: SMOD image
        forest: Forest mask image
        year: Year string for naming

    Returns:
        Classification image
    """
    # Reclassify SMOD
    # Urban Centre (30) -> 1
    # Urban Cluster (21, 22, 23) -> 2
    # Rural (10, 11, 12, 13) -> 3

    urban = smod.eq(30)
    periUrban = smod.eq(21).Or(smod.eq(22)).Or(smod.eq(23))
    rural = smod.eq(10).Or(smod.eq(11)).Or(smod.eq(12)).Or(smod.eq(13))

    # Create base classification
    classification = (ee.Image(0)
        .where(rural, 3)           # Rural
        .where(periUrban, 2)       # Peri-Urban
        .where(urban, 1)           # Urban
        .where(forest.And(rural.Or(smod.eq(10))), 4)  # Natural Forest
        .clip(aoi)
        .rename(f'classification_{year}'))

    return classification.toByte()

# Create fused classifications for 2008 and 2018
fused2008 = createFusedClassification(smod_2008, forest2008, '2008')
fused2018 = createFusedClassification(smod_2018, forest2018, '2018')

print('✅ Classification created for 2008 and 2018\n')

# =====================================================
# MERGE BOTH DATA INTO SINGLE MULTI-BAND IMAGE
# =====================================================

print('📦 Merging datasets...')

mergedData = (fused2008.rename('classification_2008')
    .addBands(fused2018.rename('classification_2018'))
    .addBands(treeCover2008.rename('treeCover_2008'))
    .addBands(treeCover2018.rename('treeCover_2018'))
    .addBands(smod_2008.rename('smod_2008'))
    .addBands(smod_2018.rename('smod_2018')))

print('✅ Merged dataset created with 6 bands\n')

# =====================================================
# VISUALIZATION PARAMETERS
# =====================================================

classificationVis = {
    'min': 1,
    'max': 4,
    'palette': [
        '#E31A1C',  # 1: Urban - Red
        '#FF7F00',  # 2: Peri-Urban - Orange
        '#FFFF99',  # 3: Rural - Light Yellow
        '#33A02C'   # 4: Natural Forest - Green
    ]
}

treeCoverVis = {
    'min': 0,
    'max': 100,
    'palette': ['#FFFFCC', '#C2E699', '#78C679', '#31A354', '#006837']
}

# =====================================================
# CREATE MAP AND ADD LAYERS
# =====================================================

print('🗺️  Creating interactive map...')

# Create interactive map
Map = geemap.Map()

# Center map on AOI
Map.centerObject(aoi, 8)

# Add 2008 layers
Map.addLayer(fused2008, classificationVis, 'Classification 2008', True)
Map.addLayer(treeCover2008, treeCoverVis, 'Tree Cover 2008', False)

# Add 2018 layers
Map.addLayer(fused2018, classificationVis, 'Classification 2018', True)
Map.addLayer(treeCover2018, treeCoverVis, 'Tree Cover 2018', False)

# Add AOI boundary
empty = ee.Image().byte()
aoiOutline = empty.paint(**{
    'featureCollection': aoi,
    'color': 1,
    'width': 2
})
Map.addLayer(aoiOutline, {'palette': '000000'}, 'AOI Boundary')

# =====================================================
# ADD LEGEND TO MAP
# =====================================================

# Create legend
legend_dict = {
    'Urban': '#E31A1C',
    'Peri-Urban': '#FF7F00',
    'Rural': '#FFFF99',
    'Natural Forest': '#33A02C'
}

# Add legend
Map.add_legend(
    title='Land Classification\n(Years: 2008 & 2018)',
    legend_dict=legend_dict,
    position='bottomleft'
)

print('✅ Map created with layers and legend\n')

# =====================================================
# EXPORT FUNCTIONS - GEOTIFF DOWNLOAD
# =====================================================

print('🚀 Starting export tasks...\n')

# Export Classification 2008
task_2008 = ee.batch.Export.image.toDrive(**{
    'image': fused2008,
    'description': 'Kerala_Classification_2008',
    'folder': 'GEE_Exports',
    'fileNamePrefix': 'Kerala_Urban_Forest_Classification_2008',
    'region': aoi.geometry(),
    'scale': 100,
    'crs': crs,
    'maxPixels': 1e13,
    'fileFormat': 'GeoTIFF'
})
task_2008.start()
print('✅ Export task started: Kerala_Classification_2008')

# Export Classification 2018
task_2018 = ee.batch.Export.image.toDrive(**{
    'image': fused2018,
    'description': 'Kerala_Classification_2018',
    'folder': 'GEE_Exports',
    'fileNamePrefix': 'Kerala_Urban_Forest_Classification_2018',
    'region': aoi.geometry(),
    'scale': 100,
    'crs': crs,
    'maxPixels': 1e13,
    'fileFormat': 'GeoTIFF'
})
task_2018.start()
print('✅ Export task started: Kerala_Classification_2018')

# Export Merged Dataset (all bands)
task_merged = ee.batch.Export.image.toDrive(**{
    'image': mergedData,
    'description': 'Kerala_Merged_Dataset_2008_2018',
    'folder': 'GEE_Exports',
    'fileNamePrefix': 'Kerala_Merged_Urban_Forest_2008_2018',
    'region': aoi.geometry(),
    'scale': 100,
    'crs': crs,
    'maxPixels': 1e13,
    'fileFormat': 'GeoTIFF'
})
task_merged.start()
print('✅ Export task started: Kerala_Merged_Dataset_2008_2018')

print('\n📁 Files will be exported to your Google Drive in "GEE_Exports" folder\n')

# =====================================================
# GENERATE DOWNLOAD URLS
# =====================================================

print('📥 GENERATING DIRECT DOWNLOAD LINKS:\n')

try:
    download2008Url = fused2008.getDownloadURL({
        'name': 'Kerala_Classification_2008',
        'scale': 100,
        'crs': crs,
        'region': aoi.geometry(),
        'format': 'GeoTIFF'
    })
    print(f'⬇️  2008 Classification:')
    print(f'{download2008Url}\n')
except Exception as e:
    print(f'❌ Error generating 2008 download URL: {e}\n')

try:
    download2018Url = fused2018.getDownloadURL({
        'name': 'Kerala_Classification_2018',
        'scale': 100,
        'crs': crs,
        'region': aoi.geometry(),
        'format': 'GeoTIFF'
    })
    print(f'⬇️  2018 Classification:')
    print(f'{download2018Url}\n')
except Exception as e:
    print(f'❌ Error generating 2018 download URL: {e}\n')

print('💡 Note: Direct download URLs may fail for large files.')
print('   Use Google Drive export tasks for reliable downloads.\n')

# =====================================================
# MONITOR EXPORT TASKS
# =====================================================

def check_task_status():
    """Check and display status of all export tasks"""
    tasks = ee.batch.Task.list()

    print('📊 EXPORT TASK STATUS:\n')
    print(f'{"Description":<40} {"State":<15} {"Progress"}')
    print('-' * 70)

    for task in tasks[:5]:  # Show last 5 tasks
        task_info = task.status()
        description = task_info.get('description', 'N/A')
        state = task_info.get('state', 'N/A')

        # Get progress if available
        progress = ''
        if state == 'RUNNING':
            progress = f"{task_info.get('progress', 0):.1f}%"

        print(f'{description:<40} {state:<15} {progress}')

    print('-' * 70)

# Initial task status check
check_task_status()

# =====================================================
# CALCULATE AREA STATISTICS
# =====================================================

print('\n🔢 CALCULATING AREA STATISTICS...\n')

class_names = ['Urban', 'Peri-Urban', 'Rural', 'Natural Forest']

def calculate_area_stats(image, year):
    """
    Calculate area statistics for each classification class

    Args:
        image: Classification image
        year: Year string
    """
    print(f'--- Area Statistics for {year} ---\n')

    results = {}

    for i in range(1, 5):
        classArea = image.eq(i).multiply(ee.Image.pixelArea()).divide(1e6)
        stats = classArea.reduceRegion(**{
            'reducer': ee.Reducer.sum(),
            'geometry': aoi.geometry(),
            'scale': 100,
            'maxPixels': 1e13
        })

        area_value = stats.getInfo().get(f'classification_{year}', 0)
        results[class_names[i-1]] = area_value
        print(f'{class_names[i-1]:<20}: {area_value:>10.2f} sq km')

    print()
    return results

# Calculate statistics
stats_2008 = calculate_area_stats(fused2008, '2008')
stats_2018 = calculate_area_stats(fused2018, '2018')

# =====================================================
# VISUALIZE AREA STATISTICS
# =====================================================

print('📊 Creating visualization charts...\n')

# Prepare data for visualization
categories = list(stats_2008.keys())
values_2008 = list(stats_2008.values())
values_2018 = list(stats_2018.values())

# Create comparison bar chart
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Bar chart
x = np.arange(len(categories))
width = 0.35

bars1 = ax1.bar(x - width/2, values_2008, width, label='2008',
                color=['#E31A1C', '#FF7F00', '#FFFF99', '#33A02C'], alpha=0.8)
bars2 = ax1.bar(x + width/2, values_2018, width, label='2018',
                color=['#E31A1C', '#FF7F00', '#FFFF99', '#33A02C'], alpha=0.5)

ax1.set_xlabel('Land Classification', fontsize=12, fontweight='bold')
ax1.set_ylabel('Area (sq km)', fontsize=12, fontweight='bold')
ax1.set_title('Land Classification Comparison: 2008 vs 2018', fontsize=14, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels(categories, rotation=45, ha='right')
ax1.legend()
ax1.grid(axis='y', alpha=0.3)

# Change detection
changes = [values_2018[i] - values_2008[i] for i in range(len(categories))]
colors_change = ['green' if c > 0 else 'red' for c in changes]

ax2.barh(categories, changes, color=colors_change, alpha=0.7)
ax2.set_xlabel('Area Change (sq km)', fontsize=12, fontweight='bold')
ax2.set_title('Area Change: 2008 to 2018', fontsize=14, fontweight='bold')
ax2.axvline(x=0, color='black', linestyle='-', linewidth=0.5)
ax2.grid(axis='x', alpha=0.3)

plt.tight_layout()
plt.show()

# Print change statistics
print('\n=== CHANGE DETECTION (2008 → 2018) ===\n')
for i, category in enumerate(categories):
    change = changes[i]
    percent_change = (change / values_2008[i] * 100) if values_2008[i] > 0 else 0
    symbol = '📈' if change > 0 else '📉' if change < 0 else '➡️'
    print(f'{symbol} {category:<20}: {change:>+10.2f} sq km ({percent_change:>+6.2f}%)')

# =====================================================
# SUMMARY INFORMATION
# =====================================================

print('\n' + '='*70)
print('=== DATA FUSION COMPLETE ===')
print('='*70)

print('\n📦 Merged Dataset Information:')
print('   Contains 6 bands:')
print('   1. classification_2008')
print('   2. classification_2018')
print('   3. treeCover_2008')
print('   4. treeCover_2018')
print('   5. smod_2008')
print('   6. smod_2018')

print('\n🗺️  Classification Legend:')
print('   1 = Urban (Red)')
print('   2 = Peri-Urban (Orange)')
print('   3 = Rural (Light Yellow)')
print('   4 = Natural Forest (Green)')

print('\n📍 Study Area: Kerala, India')
print(f'   CRS: {crs}')
print(f'   Resolution: 100m')

print('\n✅ Next Steps:')
print('   1. View the interactive map below')
print('   2. Check export tasks in your Google Drive')
print('   3. Download GeoTIFF files from Drive folder "GEE_Exports"')
print('   4. Or use direct download URLs (if generated above)')

print('\n' + '='*70)

# Display the map at the end
Map